apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: vt-api
  name: vt-api
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vt-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vt-api
    spec:
      containers:
        - image: registry.digitalocean.com/vt-registry/vt-api:e2e94b11f634e237f2c938fb310c9ecbf9dedc2f
          imagePullPolicy: Always
          name: vt-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
          - name: LAST_MAN_DEPLOY
            value: "2-2-2024"
          - name: NODE_ENV
            value: "production"
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: vt-secrets
                key: app_key
          - name: APP_BASE_API_URL
            value: "https://api-dev.vistatable.com"
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: vt-secrets
                key: db_connection_string
          - name: DB_CERT
            valueFrom:
              secretKeyRef:
                name: vt-secrets
                key: db_cert
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: vt-secrets
                key: jwt_secret
          - name: JWT_ACCESS_TOKEN_EXPIRY
            value: "23h"
          - name: JWT_VERIFICATION_TOKEN_EXPIRY
            value: "72h"
          - name: CRYPTO_KEY_LENGTH
            value: "64"
          - name: CRYPTO_SALT_SIZE
            value: "16"
          - name: EMAIL_PROVIDER_API_KEY
            valueFrom:
              secretKeyRef:
                name: vt-secrets
                key: email_provider_api_key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30