-- ####################################
-- OpenZooSim Official Schema 
-- VERSION: 20240715_v1
--
-- https://openzoosim.com
--
-- Licensed Under MIT.
-- Copyright 2024. OpenZooSim. All Rights Reserved.
-- 
-- This will allow you to create a new (empty) 
-- database from scratch to get started. You 
-- should run these in order.
-- ####################################

-- AUTH

CREATE TABLE IF NOT EXISTS "banned_ips" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "ip" text UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS "user_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "name" text NOT NULL,
  "key" text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "email" text UNIQUE NOT NULL,
  "username" text NOT NULL,
  "is_verified" boolean DEFAULT false,
  "user_type_id" integer,
  "password_hash" text,
  "last_login" timestamp,
  "failed_login_attempts" integer DEFAULT 0,
  "is_banned" boolean DEFAULT false,
  "ban_reason" text,
  "can_use_api_keys" boolean DEFAULT false
);

ALTER TABLE "users" ADD FOREIGN KEY ("user_type_id") REFERENCES "user_types" ("id");

CREATE TABLE IF NOT EXISTS "user_login_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" integer
);

ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "user_id" INTEGER,
  "ip" text NOT NULL,
  "device_thumbprint" text NOT NULL,
  "session_token" text NOT NULL,
  "expires_at" timestamp
);

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_password_resets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" INTEGER,
  "token" text UNIQUE NOT NULL,
  "expires_at" timestamp
);

ALTER TABLE "user_password_resets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_api_keys" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" integer,
  "api_key" text UNIQUE NOT NULL
);

ALTER TABLE "user_api_keys" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
